import os
import pathlib

import mantid.simpleapi as mtd_api
import numpy as np
import pytest

mtd_api.config["default.facility"] = "SNS"
mtd_api.config["default.instrument"] = "REF_L"

from lr_reduction.scaling_factors import workflow as sf_workflow
from lr_reduction.utils import amend_config

# Per-field comparison bars, measured against UNCONTAMINATED references.
#
# Read the history before touching these. v1 of this slug set the fitted bars
# to 1e-3 from a "worst observed delta" of ~5.6e-05 on `a` and 6.7e-04 on `b`,
# and explained `b`'s size as "a near-zero slope, so relative error is noisier".
# Both the number and the explanation were wrong, for the same reason:
# sf_197912_Si_dt_par_46_300.cfg was a byte-identical COPY of the _200 file
# (md5 14d3e256... for both), so `test_compute_sf_with_deadtime_tof_300` was
# comparing a 300-step computation against a 200-step reference. The entire
# tolerance budget was the physical 200->300 binning difference, read as fit
# noise. Regenerating the 300 reference from a real 300-step run reproduces
# that difference exactly — b 6.748e-04, a 5.648e-05, error_a 3.046e-05,
# error_b 2.268e-05 — which is what those v1 "noise" figures actually were.
#
# With all four references distinct, worst relative delta per case:
#
#   case                                          a         b   error_a   error_b
#   test_compute_sf                        1.80e-14  3.36e-14  6.73e-14  5.18e-14
#   ..._with_deadtime                      8.43e-13  4.64e-11  4.28e-12  4.26e-12
#   ..._with_deadtime_tof_200              9.58e-14  2.88e-12  1.68e-12  1.42e-12
#   ..._with_deadtime_tof_200_sort         9.58e-14  2.88e-12  1.68e-12  1.42e-12
#   ..._with_deadtime_tof_300              0.00e+00  0.00e+00  0.00e+00  0.00e+00
#
# The five instrument-metadata fields (LambdaRequested, S1H, S2iH, S1W, S2iW)
# are 0.0 in every case. Five, not nine — nine is the count of NUMERIC fields,
# five metadata plus four fitted.
#
# **What those deltas are.** Not run-to-run noise: on one build the fits
# reproduce EXACTLY, 0.0 to the last bit, which is why the tof_300 column above
# is all zeros — that reference was regenerated by today's build. The other
# three references date to ce1a3ae (2025-12-03), so their ~1e-11 columns are
# **cross-build drift**. That is better evidence for a cross-platform bar than
# run-to-run scatter would be, because it is the very thing the bar has to
# absorb. (v2's comment called it "on this platform the fits reproduce to
# ~1e-11" — the number was right and the sentence was wrong.)
#
# Read the per-case numbers as single-sample order statistics: each is one
# maximum over 9 rows, and regenerating any reference reshuffles them. They
# bound the scale; they are not a distribution.
#
# **The honest headroom figure is 2336x.** Quoting "rtol / worst-relative-delta"
# invites a maintainer to reproduce a number that is not what governs
# flakiness. What governs it is the TIGHTEST single comparison in the suite:
# min(bar / |delta|) over every field of every row of all five cases, which is
# error_a row 0 of _42_200 — |delta| 1.998e-13 against a bar of 4.668e-10.
# Anything that shrinks that margin is what turns the suite red.
#
# **Why the regenerated reference is not circular.** The 300 baseline was
# produced by the code under test, so it cannot prove the physics — but the
# data answers the concern anyway. The binning effect tracks the dead-time
# correction across three decades and vanishes where the correction vanishes:
#
#   row  S1H     a         dt effect   bin effect   bin/dt
#   0    0.391      1.105   3.42e-04     2.09e-08   6.1e-05
#   4    0.770     56.961   8.95e-02     2.72e-05   3.0e-04
#   8    3.016   1251.159   2.25e-01     5.48e-05   2.4e-04
#
# A roughly flat ~1e-4 ratio over a correction spanning 0.03% to 22.5% is the
# signature of a real binning difference; a wrong parameter or a wrong code
# path does not produce that structure. It is also why the duplicate survived
# unnoticed for so long: `a` moving 5.6e-05 is ~5e-4 of a correction that is
# itself up to 22.5%.
#
# The bars below are therefore a cross-platform allowance for a build we have
# not measured, sized well above observed cross-build drift and still about six
# orders inside the fit's OWN uncertainty: error_a/a runs 1.74%-4.39% across
# the 36 reference rows. A regression large enough to matter scientifically
# cannot hide under them, and v1's 1e-3 — which would have passed a 0.1% shift
# in the scaling factor that multiplies every R(Q) — cannot recur.
#
# Comparison is hybrid, `|calc - ref| <= atol + rtol * |ref|`, for every field:
# `b` spans 4.8 decades across the references (5.537e-07 to 3.449e-02) and some
# rows sit within 1 sigma of zero, where a pure relative bar is meaningless.
# The atol is what handles that; v1 instead had a `v_ref == 0.0` branch that
# compared an ABSOLUTE delta against a RELATIVE bar, and which no reference row
# could ever reach.
#
# If CI on another platform exceeds these, widen from THAT measurement and
# record it — never to turn a red suite green. That is the mistake this comment
# exists to prevent repeating, and `b` carries a hard ceiling (below) where
# widening would start destroying a different guard.
_METADATA = (1e-12, 0.0)      # copied verbatim from run logs; must round-trip
_FITTED = (1e-8, 0.0)         # least-squares outputs
_TOL = {
    "LambdaRequested": _METADATA,
    "S1H": _METADATA,
    "S2iH": _METADATA,
    "S1W": _METADATA,
    "S2iW": _METADATA,
    "a": _FITTED,
    "error_a": _FITTED,
    "error_b": _FITTED,
    # b is looser than its siblings for a measured reason, not a hunch. A
    # converged b is path-dependent: with identical input data, swapping only
    # Mantid's minimizer from the default Levenberg-MarquardtMD to
    # Levenberg-Marquardt — the same family, the same optimum, a different
    # internal route — moves b by 8.657e-11 (a 1.366e-11, error_a 8.755e-12,
    # error_b 7.964e-12). Measured, not quoted:
    # plan/scripts/measure_fit_path_dependence.py reproduces it from this repo.
    # A bar below a field's floor tests the minimizer rather than the data, so
    # 1e-8 would sit only ~115x over b's floor; 1e-7 is ~1155x over it and still
    # at least five orders inside b's own uncertainty (b/error_b runs
    # 0.425-8.586 across the references).
    #
    # That probe also runs Simplex as a control, where b moves ~59%. That is
    # NOT part of the floor: Simplex is a different algorithm with a looser
    # stopping criterion, not a different path to the same optimum, and folding
    # it in would "justify" a bar six orders too loose. A real measurement
    # answering the wrong question is exactly what produced this slug's v1.
    #
    # CEILING: two bars gate the _46_200/_46_300 pair, and neither alone makes
    # test_reference_files_are_pairwise_distinguishable vacuous — the other still
    # catches it. Crossing BOTH reopens the hole v2 closed.
    #   b's rtol must stay below 6.743e-04  (the physical 200->300 binning
    #                                        difference on the slope)
    #   _FITTED must stay below 5.648e-05   (the same difference on `a`; _FITTED
    #                                        also covers error_a 3.047e-05 and
    #                                        error_b 2.268e-05)
    # Verified: b alone at 1e-2 still leaves the pair distinguishable via `a`.
    #
    # The 1e-12 absolute term is ~6 orders below the smallest |b| in any
    # reference and ~6 orders below error_b, so it only ever governs a
    # genuinely near-zero slope, where the relative delta carries no
    # information.
    "b": (1e-7, 1e-12),
}


def _parse_cfg(path):
    """
    Parse a scaling-factor cfg into one dict of {field: value-string} per row,
    skipping comments and blank lines.

    Duplicate keys within a row are an error rather than a silent last-wins
    overwrite — that silent-collapse is the exact class of bug this helper was
    fixed for, and dict() would reintroduce it one level down.
    """
    rows = []
    with open(path, "r") as fd:
        for lineno, line in enumerate(fd, 1):
            if line.startswith("#") or not line.strip():
                continue
            pairs = [tok.split("=", 1) for tok in line.split() if "=" in tok]
            keys = [k for k, _ in pairs]
            duplicates = sorted({k for k in keys if keys.count(k) > 1})
            assert not duplicates, f"{path} line {lineno}: duplicate field(s) {duplicates}"
            rows.append(dict(pairs))
    return rows


def check_results(data_file, reference):
    """
    Check every field of a scaling factor file against its reference.

    Fields are compared per key against the per-field `(rtol, atol)` bar in
    `_TOL`; non-numeric fields (IncidentMedium) are compared exactly. The row
    count, each row's field set, and the field ORDER are all checked.

    Returns the number of field comparisons performed, so a caller can assert
    the helper actually did the work — a helper that silently compares nothing
    is what this slug exists to fix, and a positive control that only asserts
    "does not raise" cannot tell the two apart.
    """
    cfg_data = _parse_cfg(data_file)
    cfg_ref = _parse_cfg(reference)

    assert len(cfg_data) == len(cfg_ref), (
        f"{data_file} has {len(cfg_data)} data rows, reference {reference} has {len(cfg_ref)}"
    )

    comparisons = 0
    for i, (row, ref) in enumerate(zip(cfg_data, cfg_ref)):
        # Order, not just membership: template.py's consumer reads this format
        # POSITIONALLY (`keys[3]`, `keys[5]` at :184-185) to stay backward
        # compatible with older S2H spellings. A writer that reordered fields
        # would keep the same set, pass a set-equality check, and then make the
        # consumer mismatch and fall through to "proceeding unscaled" — a
        # plausible, silently unscaled R(Q).
        assert list(row) == list(ref), (
            f"row {i}: field order differs from the reference; "
            f"got {list(row)} expected {list(ref)}"
        )
        for key, ref_str in ref.items():
            value_str = row[key]
            try:
                v_ref = float(ref_str)
            except ValueError:
                assert value_str == ref_str, f"row {i} {key}: {value_str!r} != reference {ref_str!r}"
                comparisons += 1
                continue
            try:
                v_calc = float(value_str)
            except ValueError:
                raise AssertionError(
                    f"row {i} {key}: {value_str!r} is not numeric but the reference {ref_str!r} is"
                )
            rtol, atol = _TOL[key]
            delta = np.fabs(v_calc - v_ref)
            bar = atol + rtol * np.fabs(v_ref)
            assert delta <= bar, (
                f"row {i} {key}: {v_calc!r} vs reference {v_ref!r} "
                f"(|delta| {delta:.3e} > {bar:.3e} = {atol:.0e} + {rtol:.0e}*|ref|)"
            )
            comparisons += 1
    return comparisons


# Every committed reference this module compares against, discovered rather
# than listed. A hand-maintained tuple is disconnected from the files it names:
# a future sf_197912_Si_dt_par_46_400.cfg that nobody remembers to add would be
# absent from the pairwise-distinguishability guard, reopening the hole that
# guard exists to close. The pattern is narrow on purpose — sf_201043_Si.cfg is
# a reduction *input*, not a reference, and is correctly excluded.
_REFERENCE_CFGS = tuple(
    sorted(p.name for p in (pathlib.Path(__file__).parent / "data").glob("sf_197912_Si*.cfg"))
)
# An empty glob would hand pytest an empty parameter set, which it reports as
# "1 skipped" — the guard would vanish silently, which is strictly worse than
# the hand-maintained tuple this replaced (that would have failed loudly).
assert len(_REFERENCE_CFGS) >= 4, (
    f"reference glob found {_REFERENCE_CFGS}; expected at least the four committed references"
)

_REF_ROWS = [
    "IncidentMedium=Si LambdaRequested=9.74 S1H=0.391 S2iH=0.25 S1W=20.005 S2iW=20.0 "
    "a=1.1051209892255538 b=-5.536686634970115e-07 error_a=0.046673303933524965 error_b=1.3017622676214164e-06",
    "IncidentMedium=Si LambdaRequested=7.043 S1H=0.39 S2iH=0.25 S1W=19.952 S2iW=19.95 "
    "a=6.624303827034047 b=1.9231042128909928e-05 error_a=0.23125978138549352 error_b=9.279372359246127e-06",
]


def _write_cfg(path, rows):
    with open(path, "w") as fd:
        fd.write("# y=a+bx\n#\n")
        fd.writelines(row + "\n" for row in rows)
    return str(path)


def _mutated(row, key, value):
    """Return `row` with `key` set to `value`, preserving field order."""
    toks = []
    for tok in row.split():
        k, _, v = tok.partition("=")
        toks.append(f"{k}={value}" if k == key else f"{k}={v}")
    return " ".join(toks)


# 2 rows x 10 fields. Asserted as a literal so that a helper which silently
# stops comparing — this slug's entire subject — fails the positive control
# instead of passing it. (The v2 review estimated 18; the rows carry ten fields
# each, IncidentMedium included, so the true count is 20.)
_EXPECTED_COMPARISONS = 20


def test_check_results_accepts_an_identical_file(tmp_path):
    """Positive control: the guards below must fail for the right reason.

    Asserts the comparison COUNT, not merely that nothing raised. "Did not
    raise" is exactly what the broken helper did.
    """
    ref = _write_cfg(tmp_path / "ref.cfg", _REF_ROWS)
    data = _write_cfg(tmp_path / "data.cfg", _REF_ROWS)
    assert check_results(data, ref) == _EXPECTED_COMPARISONS


def test_tol_covers_every_numeric_reference_field():
    """A field missing from _TOL must be a loud error, not a loose default.

    v1 carried a `_DEFAULT_TOL = 1e-3` fallback, so a single typo — `"S1W"`
    written `"S1w"` — would have silently demoted a bit-exact metadata field to
    a bar nine orders looser, with the suite green. There is no fallback now;
    this pins the keyset so the failure surfaces here rather than as a KeyError
    mid-reduction-test.
    """
    fields = list(_parse_cfg(os.path.join(os.path.dirname(__file__), "data", "sf_197912_Si_auto.cfg"))[0])
    string_fields = {"IncidentMedium"}
    assert set(_TOL) == set(fields) - string_fields
    assert set(_TOL).isdisjoint(string_fields)


@pytest.mark.parametrize(
    "left, right",
    [
        pytest.param(a, b, id=f"{a}--vs--{b}")
        for i, a in enumerate(_REFERENCE_CFGS)
        for b in _REFERENCE_CFGS[i + 1 :]
    ],
)
def test_reference_files_are_pairwise_distinguishable(template_dir, left, right):
    """No two committed references may be interchangeable.

    `sf_197912_Si_dt_par_46_300.cfg` was a byte-identical copy of the _200 file
    (md5 14d3e256... for both), so the 300-step test compared a 300-step
    computation against a 200-step reference and could not fail no matter what
    the code did with `DeadTimeTOFStep`. One `md5sum` would have caught it; this
    is that check, expressed in the terms the suite actually cares about —
    each pair must differ on at least one field `check_results` compares, which
    is stronger than "the bytes differ" (a header-only difference would not
    count).
    """
    with pytest.raises(AssertionError):
        check_results(os.path.join(template_dir, left), os.path.join(template_dir, right))


def test_check_results_detects_a_field_reorder(tmp_path):
    """Field ORDER is part of the format, because the consumer reads it positionally.

    `template.py:184-185` takes `keys[3]` and `keys[5]` to stay compatible with
    older S2H spellings. A writer that reordered fields would preserve the field
    SET, sail past a set-equality check, and then mismatch in the consumer —
    which does not raise but falls through to `template.py:207` "proceeding
    unscaled", producing a plausible and silently unscaled R(Q).
    """
    ref = _write_cfg(tmp_path / "ref.cfg", _REF_ROWS)
    toks = _REF_ROWS[1].split()
    swapped = " ".join([toks[0]] + [toks[2], toks[1]] + toks[3:])
    data = _write_cfg(tmp_path / "data.cfg", [_REF_ROWS[0], swapped])
    with pytest.raises(AssertionError):
        check_results(data, ref)


def test_check_results_rejects_a_duplicate_field(tmp_path):
    """A repeated key must not silently last-wins into the dict."""
    ref = _write_cfg(tmp_path / "ref.cfg", _REF_ROWS)
    # The injected duplicate carries the REFERENCE value, so the value
    # comparison cannot raise and only the duplicate guard can. v2 injected
    # a=999999.0, which is also value-wrong — that test passed with the guard
    # deleted, i.e. it could not fail for its stated reason. That is the exact
    # class of defect this slug exists to fix, introduced while fixing it.
    data = _write_cfg(tmp_path / "data.cfg", [_REF_ROWS[0], _REF_ROWS[1] + " a=6.624303827034047"])
    with pytest.raises(AssertionError):
        check_results(data, ref)


@pytest.mark.parametrize(
    "key, value",
    [
        # Gross corruption. Every one of these went UNDETECTED before this fix.
        pytest.param("a", "999999.0", id="a-the-scaling-factor-itself"),
        pytest.param("b", "999999.0", id="b-the-slope"),
        pytest.param("error_a", "999999.0", id="error_a-uncertainty-on-a"),
        pytest.param("LambdaRequested", "999.0", id="LambdaRequested-the-row-s-wavelength"),
        pytest.param("S1W", "999.0", id="S1W-slit-width"),
        # float() would raise on this one rather than compare it.
        pytest.param("IncidentMedium", "Air", id="IncidentMedium-non-numeric"),
        # The mirror case, which the one above does NOT cover: a numeric
        # reference against a non-numeric value takes the other branch, where
        # float(value_str) raises and must become an AssertionError rather than
        # a bare ValueError escaping the helper.
        pytest.param("a", "n/a", id="a-non-numeric-under-a-numeric-reference"),
        # Subtle, and the reason the tolerances were measured rather than
        # inherited: a 1% error in `a` passes the old 0.02 bar even if `a` had
        # been compared at all.
        pytest.param("a", "6.690546865304387", id="a-1pc-high-under-the-old-0.02-bar"),
        # 0.04 mm on a 20 mm slit: the exact discrepancy that exposed the stale
        # row in sf_197912_Si_auto.cfg. Metadata is copied from the run logs, so
        # this must fail, not be absorbed by a fitted-parameter tolerance.
        pytest.param("S1W", "19.992", id="S1W-0.04mm-the-stale-reference-delta"),
    ],
)
def test_check_results_detects_mutation(tmp_path, key, value):
    ref = _write_cfg(tmp_path / "ref.cfg", _REF_ROWS)
    mutated = [_REF_ROWS[0], _mutated(_REF_ROWS[1], key, value)]
    data = _write_cfg(tmp_path / "data.cfg", mutated)
    with pytest.raises(AssertionError):
        check_results(data, ref)


def test_check_results_detects_a_missing_field(tmp_path):
    """A field that vanishes from the output is a regression, not a pass."""
    ref = _write_cfg(tmp_path / "ref.cfg", _REF_ROWS)
    dropped = " ".join(t for t in _REF_ROWS[1].split() if not t.startswith("error_a="))
    data = _write_cfg(tmp_path / "data.cfg", [_REF_ROWS[0], dropped])
    with pytest.raises(AssertionError):
        check_results(data, ref)


def test_check_results_detects_a_truncated_file(tmp_path):
    """Fewer rows than the reference must fail, not silently compare a prefix."""
    ref = _write_cfg(tmp_path / "ref.cfg", _REF_ROWS)
    data = _write_cfg(tmp_path / "data.cfg", _REF_ROWS[:1])
    with pytest.raises(AssertionError):
        check_results(data, ref)


def test_compute_sf(nexus_dir, template_dir, tmp_path):
    """
    Test the computation of scaling factors
    """
    with amend_config(data_dir=nexus_dir):
        ws = mtd_api.Load("REF_L_197912")

    output_dir = str(tmp_path)

    # We are passing the first run of the set. For the autoreduction,
    # we would be missing runs from the complete set so we will want to
    # wait for the whole set to be acquired.
    output = sf_workflow.process_scaling_factors(ws, output_dir, use_deadtime=False, wait=True, postfix="_test")
    assert output is False

    output_cfg = os.path.join(output_dir, "sf_197912_Si_test.cfg")
    if os.path.isfile(output_cfg):
        os.remove(output_cfg)

    output = sf_workflow.process_scaling_factors(ws, output_dir, use_deadtime=False, wait=False, postfix="_test")
    assert output is True

    check_results(output_cfg, os.path.join(template_dir, "sf_197912_Si_auto.cfg"))


def test_compute_sf_with_deadtime(nexus_dir, template_dir, tmp_path):
    """
    Test the computation of scaling factors
    """
    with amend_config(data_dir=nexus_dir):
        ws = mtd_api.Load("REF_L_197912")

    output_dir = str(tmp_path)

    output_cfg = os.path.join(output_dir, "sf_197912_Si_test_dt.cfg")
    if os.path.isfile(output_cfg):
        os.remove(output_cfg)

    output = sf_workflow.process_scaling_factors(ws, output_dir, use_deadtime=True, wait=False, postfix="_test_dt")
    assert output is True

    check_results(output_cfg, os.path.join(template_dir, "sf_197912_Si_dt_par_42_200.cfg"))


def test_compute_sf_with_deadtime_tof_300(nexus_dir, template_dir, tmp_path):
    """
    Test the computation of scaling factors
    """
    with amend_config(data_dir=nexus_dir):
        ws = mtd_api.Load("REF_L_197912")

    output_dir = str(tmp_path)

    output_cfg = os.path.join(output_dir, "sf_197912_Si_test_dt.cfg")
    if os.path.isfile(output_cfg):
        os.remove(output_cfg)

    output = sf_workflow.process_scaling_factors(
        ws,
        output_dir,
        use_deadtime=True,
        deadtime=4.6,
        deadtime_tof_step=300,
        paralyzable=False,
        wait=False,
        postfix="_test_dt",
    )
    assert output is True

    check_results(output_cfg, os.path.join(template_dir, "sf_197912_Si_dt_par_46_300.cfg"))


def test_compute_sf_with_deadtime_tof_200(nexus_dir, template_dir, tmp_path):
    """
    Test the computation of scaling factors
    """
    with amend_config(data_dir=nexus_dir):
        ws = mtd_api.Load("REF_L_197912")

    output_dir = str(tmp_path)

    output_cfg = os.path.join(output_dir, "sf_197912_Si_test_dt.cfg")
    if os.path.isfile(output_cfg):
        os.remove(output_cfg)

    output = sf_workflow.process_scaling_factors(
        ws,
        output_dir,
        use_deadtime=True,
        deadtime=4.6,
        deadtime_tof_step=200,
        paralyzable=False,
        wait=False,
        postfix="_test_dt",
    )
    assert output is True

    check_results(output_cfg, os.path.join(template_dir, "sf_197912_Si_dt_par_46_200.cfg"))


def test_compute_sf_with_deadtime_tof_200_sort(nexus_dir, template_dir, tmp_path):
    """
    Test the computation of scaling factors with order_by_runs=False.

    Pre-existing limitation, recorded rather than fixed here: this compares
    against the SAME reference as its `order_by_runs=True` sibling, and the two
    outputs are byte-identical, so `order_by_runs=False` is not actually
    exercised. For this run set the two orderings coincide; distinguishing them
    needs a set whose run order and sort order differ, which is a data question,
    not a helper one. Named explicitly because an unremarked duplicate
    reference is exactly what this slug's v1 shipped.
    """
    with amend_config(data_dir=nexus_dir):
        ws = mtd_api.Load("REF_L_197912")

    output_dir = str(tmp_path)

    output_cfg = os.path.join(output_dir, "sf_197912_Si_test_dt.cfg")
    if os.path.isfile(output_cfg):
        os.remove(output_cfg)

    output = sf_workflow.process_scaling_factors(
        ws,
        output_dir,
        order_by_runs=False,
        use_deadtime=True,
        deadtime=4.6,
        deadtime_tof_step=200,
        paralyzable=False,
        wait=False,
        postfix="_test_dt",
    )
    assert output is True

    check_results(output_cfg, os.path.join(template_dir, "sf_197912_Si_dt_par_46_200.cfg"))
